/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.mobileapp;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Ralph
 */
public class changePasswordFrame extends javax.swing.JFrame {

    private int clientId = 0;
    private String fullName = "";
    private String firstName = "";

    /**
     * Creates new form changePasswordFrame
     */
    public changePasswordFrame() {
        initComponents();
    }

    public changePasswordFrame(int clientId, String fullName, String firstName) {
        this.clientId = clientId;
        this.fullName = fullName;
        this.firstName = firstName;
        initComponents();
        errorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        oldPwLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        oldPasswordInput = new javax.swing.JPasswordField();
        newPasswordInput = new javax.swing.JPasswordField();
        repeatNewPasswordInput = new javax.swing.JPasswordField();
        cancelBtn = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Password");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/pass.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 250, 160, 170);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setText("Input Old/New Password");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 410, 140, 14);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Change Password");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 400, 230);

        oldPwLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        oldPwLabel.setText("Old Password");
        jPanel1.add(oldPwLabel);
        oldPwLabel.setBounds(80, 440, 260, 20);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("New Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 500, 260, 17);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Repeat New Password");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 560, 260, 17);

        oldPasswordInput.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        oldPasswordInput.setForeground(java.awt.Color.lightGray);
        oldPasswordInput.setText("1234567890");
        oldPasswordInput.setBorder(null);
        oldPasswordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                oldPasswordInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                oldPasswordInputFocusLost(evt);
            }
        });
        jPanel1.add(oldPasswordInput);
        oldPasswordInput.setBounds(80, 460, 260, 40);

        newPasswordInput.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        newPasswordInput.setForeground(java.awt.Color.lightGray);
        newPasswordInput.setText("1234567890");
        newPasswordInput.setBorder(null);
        newPasswordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newPasswordInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newPasswordInputFocusLost(evt);
            }
        });
        jPanel1.add(newPasswordInput);
        newPasswordInput.setBounds(80, 520, 260, 40);

        repeatNewPasswordInput.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        repeatNewPasswordInput.setForeground(java.awt.Color.lightGray);
        repeatNewPasswordInput.setText("1234567890");
        repeatNewPasswordInput.setBorder(null);
        repeatNewPasswordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                repeatNewPasswordInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                repeatNewPasswordInputFocusLost(evt);
            }
        });
        repeatNewPasswordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                repeatNewPasswordInputKeyReleased(evt);
            }
        });
        jPanel1.add(repeatNewPasswordInput);
        repeatNewPasswordInput.setBounds(80, 580, 260, 40);

        cancelBtn.setBackground(java.awt.Color.lightGray);
        cancelBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn);
        cancelBtn.setBounds(140, 650, 90, 40);

        errorLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        errorLabel.setForeground(java.awt.Color.red);
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText("New password does not match");
        jPanel1.add(errorLabel);
        errorLabel.setBounds(80, 620, 260, 20);

        btnSubmit.setBackground(new java.awt.Color(38, 166, 154));
        btnSubmit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSubmit.setText("Proceed");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(250, 650, 90, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/BG_LandPage.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-10, 210, 420, 530);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/Changepass_Banner.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 416, 260);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("Old Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 440, 260, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
        new homeFrame(clientId).setVisible(true);

    }//GEN-LAST:event_cancelBtnActionPerformed

    private void oldPasswordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oldPasswordInputFocusGained
        if (oldPasswordInput.getText().equals("1234567890")) {
            oldPasswordInput.setText("");
            oldPasswordInput.setForeground(Color.black);
        }
    }//GEN-LAST:event_oldPasswordInputFocusGained

    private void newPasswordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordInputFocusGained
        if (newPasswordInput.getText().equals("1234567890")) {
            newPasswordInput.setText("");
            newPasswordInput.setForeground(Color.black);
        }
    }//GEN-LAST:event_newPasswordInputFocusGained

    private void repeatNewPasswordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repeatNewPasswordInputFocusGained
        if (repeatNewPasswordInput.getText().equals("1234567890")) {
            repeatNewPasswordInput.setText("");
            repeatNewPasswordInput.setForeground(Color.black);
        }
    }//GEN-LAST:event_repeatNewPasswordInputFocusGained

    private void oldPasswordInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oldPasswordInputFocusLost
        if (oldPasswordInput.getText().equals("")) {
            oldPasswordInput.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            oldPasswordInput.setBorder(BorderFactory.createLineBorder(Color.green));
        }
    }//GEN-LAST:event_oldPasswordInputFocusLost

    private void newPasswordInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordInputFocusLost
        if (newPasswordInput.getText().equals("")) {
            newPasswordInput.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            newPasswordInput.setBorder(BorderFactory.createLineBorder(Color.green));
        }
    }//GEN-LAST:event_newPasswordInputFocusLost

    private void repeatNewPasswordInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repeatNewPasswordInputFocusLost
        if (repeatNewPasswordInput.getText().equals("")) {
            repeatNewPasswordInput.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            repeatNewPasswordInput.setBorder(BorderFactory.createLineBorder(Color.green));
        }
    }//GEN-LAST:event_repeatNewPasswordInputFocusLost

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String getPassword = "";
        getPassword = Client.getPassword(this.clientId);
        String newPassword = "", encryptedPassword = "", oldPassword = "";
        int confirm = 0, result = 0;
        oldPassword = new String(oldPasswordInput.getPassword());
        if (newPasswordInput.getText().equals(repeatNewPasswordInput.getText())) {
            if (getPassword.equals(PasswordHasher.passwordHasher(oldPassword))) {
                newPassword = new String(newPasswordInput.getPassword());
                encryptedPassword = PasswordHasher.passwordHasher(newPassword);
                confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to change your password?", "Confirm", JOptionPane.YES_NO_OPTION);

                if (confirm == 0) {
                    Client.changePassword(encryptedPassword, clientId);
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Password changed successfully.");
                    new homeFrame(clientId).setVisible(true);
                }
            } else {
                errorLabel.setText("Old password is incorrect");
                errorLabel.setVisible(true);
            }
        }


    }//GEN-LAST:event_btnSubmitActionPerformed

    private void repeatNewPasswordInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_repeatNewPasswordInputKeyReleased
        if (!newPasswordInput.getText().equals(repeatNewPasswordInput.getText())) {
            errorLabel.setText("New password does not match");
            errorLabel.setVisible(true);
            repeatNewPasswordInput.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            errorLabel.setVisible(false);
            repeatNewPasswordInput.setBorder(BorderFactory.createLineBorder(Color.green));
        }
    }//GEN-LAST:event_repeatNewPasswordInputKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changePasswordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newPasswordInput;
    private javax.swing.JPasswordField oldPasswordInput;
    private javax.swing.JLabel oldPwLabel;
    private javax.swing.JPasswordField repeatNewPasswordInput;
    // End of variables declaration//GEN-END:variables
}
