/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.mobileapp;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;

/**
 *
 * @author Ralph
 */
public class fundTransferFrame extends javax.swing.JFrame {

    private int clientId = 0;
    private String fullName = "";
    private String firstName = "";

    /**
     * Creates new form fundTransferFrame
     */
    public fundTransferFrame() {
        initComponents();
    }

    public fundTransferFrame(int userId, String firstName, String fullName) {
        initComponents();
        this.clientId = userId;
        this.fullName = fullName;
        this.firstName = firstName;
        errorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        targetAccountNumberInput = new javax.swing.JTextField();
        pinInput = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fund Transfer");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 80, 290, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/FundTransfer_Banner.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 416, 260);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/fund_trans.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 260, 140, 150);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/right-arrow.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 330, 40, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/password.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 260, 160, 150);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setText("Input Pin 1");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(290, 410, 70, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setText("Input Account Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 410, 120, 30);

        targetAccountNumberInput.setForeground(java.awt.Color.lightGray);
        targetAccountNumberInput.setText("Receipient's Account Number");
        targetAccountNumberInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                targetAccountNumberInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                targetAccountNumberInputFocusLost(evt);
            }
        });
        targetAccountNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetAccountNumberInputActionPerformed(evt);
            }
        });
        targetAccountNumberInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                targetAccountNumberInputKeyTyped(evt);
            }
        });
        jPanel1.add(targetAccountNumberInput);
        targetAccountNumberInput.setBounds(70, 460, 270, 40);

        pinInput.setForeground(java.awt.Color.lightGray);
        pinInput.setText("PIN");
        pinInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pinInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pinInputFocusLost(evt);
            }
        });
        pinInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinInputActionPerformed(evt);
            }
        });
        pinInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinInputKeyTyped(evt);
            }
        });
        jPanel1.add(pinInput);
        pinInput.setBounds(70, 520, 270, 40);

        errorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        errorLabel.setForeground(java.awt.Color.red);
        errorLabel.setText("jLabel8");
        jPanel1.add(errorLabel);
        errorLabel.setBounds(70, 570, 270, 17);

        submitButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        submitButton.setText("Proceed");
        submitButton.setBorder(null);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton);
        submitButton.setBounds(250, 610, 90, 40);

        cancelButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBorder(null);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton);
        cancelButton.setBounds(150, 610, 93, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/BG_LandPage.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 220, 420, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void targetAccountNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetAccountNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetAccountNumberInputActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        if (!pinInput.getText().trim().isEmpty() && !targetAccountNumberInput.getText().trim().isEmpty() && !pinInput.getText().trim().equals("PIN") && !targetAccountNumberInput.getText().trim().equals("Receipient's Account Number")) {
            int pin = 0, targetAccountNumber = 0;
            boolean isCorrect, isExist;
            try {
                pin = Integer.parseInt(pinInput.getText().trim());
            } catch (NumberFormatException nfe) {
                errorLabel.setText("Input your pin properly, use numbers only.");
                errorLabel.setVisible(true);
                System.out.println(nfe.getMessage());
            }
            try {
                targetAccountNumber = Integer.parseInt(targetAccountNumberInput.getText().trim());
            } catch (NumberFormatException nfe) {
                errorLabel.setText("Input the account number properly, use numbers only.");
                errorLabel.setVisible(true);
                System.out.println(nfe.getMessage());
            }
            try {
                    errorLabel.setVisible(false);
                if (Client.checkIfAccountExists(targetAccountNumber)) {
                } else {
                    System.out.println("does not exist");
                    errorLabel.setText("Account number does not exist");
                    errorLabel.setVisible(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(fundTransferFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (targetAccountNumberInput.getText().trim().isEmpty() || targetAccountNumberInput.getText().trim().equals("Receipient's Account Number")) {
            errorLabel.setText("Enter the receipient's account number");
            errorLabel.setVisible(true);
        } else if (pinInput.getText().trim().isEmpty() || pinInput.getText().trim().equals("PIN")) {
            errorLabel.setText("Enter your pin to continue");
            errorLabel.setVisible(true);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
        new homeFrame(clientId, firstName, fullName).setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void targetAccountNumberInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_targetAccountNumberInputFocusGained
        if (targetAccountNumberInput.getText().equals("Receipient's Account Number")) {
            targetAccountNumberInput.setText("");
            targetAccountNumberInput.setForeground(Color.black);
        }
    }//GEN-LAST:event_targetAccountNumberInputFocusGained

    private void targetAccountNumberInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_targetAccountNumberInputFocusLost
        if (targetAccountNumberInput.getText().equals("")) {
            targetAccountNumberInput.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            targetAccountNumberInput.setBorder(BorderFactory.createLineBorder(Color.green));
        }
    }//GEN-LAST:event_targetAccountNumberInputFocusLost

    private void pinInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinInputFocusGained
        if (pinInput.getText().equals("PIN")) {
            pinInput.setText("");
            pinInput.setForeground(Color.black);
        }
    }//GEN-LAST:event_pinInputFocusGained

    private void pinInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinInputFocusLost
        if (pinInput.getText().equals("")) {
            pinInput.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            pinInput.setBorder(BorderFactory.createLineBorder(Color.green));
        }
    }//GEN-LAST:event_pinInputFocusLost

    private void pinInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinInputActionPerformed

    private void pinInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinInputKeyTyped
        if (pinInput.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_pinInputKeyTyped

    private void targetAccountNumberInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_targetAccountNumberInputKeyTyped
        if (targetAccountNumberInput.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_targetAccountNumberInputKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fundTransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fundTransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fundTransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fundTransferFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fundTransferFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pinInput;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField targetAccountNumberInput;
    // End of variables declaration//GEN-END:variables
}
