/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.mobileapp;

import javax.swing.JOptionPane;
import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author Ralph
 */
public class homeFrame extends javax.swing.JFrame {

    private String fullName;
    private int clientId;
    private String firstName;
    private double balance;
    private double expectedBalance;

    /**
     * Creates new form homeFrame
     */
    public homeFrame() {
        initComponents();
    }

    public homeFrame(int userId) {
        this.clientId = userId;
        initComponents();

        if (Client.checkIfNew(clientId)) {
            JOptionPane.showMessageDialog(this, "Please change your password immediately", "Change Password", JOptionPane.WARNING_MESSAGE);
        }

        greetingLabel.setText("Hi, " + Client.getFirstName(clientId));
        fullNameLabel.setText(Client.createFullName(clientId));
        this.balance = Client.getBalance(clientId);
        NumberFormat format = NumberFormat.getCurrencyInstance(Locale.US);
        String formattedBalance = format.format(balance);

        balanceLabel.setText(formattedBalance);
        
        this.expectedBalance = Client.getExpectedBalance(clientId);
        String formattedExpectedBalance = format.format(expectedBalance);
        expectedBalLabel.setText(formattedExpectedBalance);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        greetingLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        forExpectedBalance = new javax.swing.JLabel();
        forCurrentBalance = new javax.swing.JLabel();
        expectedBalLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        withdrawButton = new javax.swing.JButton();
        viewTransactionsButton = new javax.swing.JButton();
        fundTransferButton = new javax.swing.JButton();
        logoutLabel = new javax.swing.JButton();
        changePassButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("University Bank");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greetingLabel.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        greetingLabel.setForeground(new java.awt.Color(255, 255, 255));
        greetingLabel.setText("Hi, Name");
        jPanel1.add(greetingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 220, 50));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/Untitled-8.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 410, 260));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/money (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, 100));

        fullNameLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        fullNameLabel.setText("Juan Dela Cruz");
        jPanel1.add(fullNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 260, 50));

        forExpectedBalance.setFont(new java.awt.Font("Calibri Light", 2, 14)); // NOI18N
        forExpectedBalance.setText("Expected Balance:");
        jPanel1.add(forExpectedBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 120, 16));

        forCurrentBalance.setFont(new java.awt.Font("Calibri Light", 2, 14)); // NOI18N
        forCurrentBalance.setText("Current Balance:");
        jPanel1.add(forCurrentBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 120, 16));

        expectedBalLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        expectedBalLabel.setForeground(new java.awt.Color(0, 153, 51));
        expectedBalLabel.setText("₱ 10,00.00");
        jPanel1.add(expectedBalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 130, -1));

        balanceLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(0, 153, 51));
        balanceLabel.setText("₱ 5,00.00");
        jPanel1.add(balanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 130, -1));

        withdrawButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        withdrawButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/payment-method.png"))); // NOI18N
        withdrawButton.setText("Cash Withdrawal Request");
        withdrawButton.setRequestFocusEnabled(false);
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });
        jPanel1.add(withdrawButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 220, 40));

        viewTransactionsButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        viewTransactionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/return-to-the-past.png"))); // NOI18N
        viewTransactionsButton.setText("View Transaction History");
        viewTransactionsButton.setRequestFocusEnabled(false);
        viewTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewTransactionsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 220, 40));

        fundTransferButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        fundTransferButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/cash-back.png"))); // NOI18N
        fundTransferButton.setText("Fund Transfer");
        fundTransferButton.setRequestFocusEnabled(false);
        fundTransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundTransferButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fundTransferButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 220, 40));

        logoutLabel.setBackground(java.awt.Color.lightGray);
        logoutLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        logoutLabel.setText("Logout");
        logoutLabel.setToolTipText("");
        logoutLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutLabelActionPerformed(evt);
            }
        });
        jPanel1.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 90, 40));

        changePassButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        changePassButton.setText("Change Password");
        changePassButton.setRequestFocusEnabled(false);
        changePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassButtonActionPerformed(evt);
            }
        });
        jPanel1.add(changePassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 220, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/BG_LandPage.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 410, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        this.dispose();
        new withdrawalFrame(this.clientId).setVisible(true);
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void viewTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionsButtonActionPerformed
        this.dispose();
        new viewTransactionsFrame(this.clientId).setVisible(true);

    }//GEN-LAST:event_viewTransactionsButtonActionPerformed

    private void fundTransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundTransferButtonActionPerformed
        this.dispose();
        new fundTransferFrame(this.clientId).setVisible(true);
    }//GEN-LAST:event_fundTransferButtonActionPerformed

    private void logoutLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutLabelActionPerformed
        this.dispose();
        new loginFrame().setVisible(true);
    }//GEN-LAST:event_logoutLabelActionPerformed

    private void changePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassButtonActionPerformed
        this.dispose();
        new changePasswordFrame(this.clientId).setVisible(true);
    }//GEN-LAST:event_changePassButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new homeFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton changePassButton;
    private javax.swing.JLabel expectedBalLabel;
    private javax.swing.JLabel forCurrentBalance;
    private javax.swing.JLabel forExpectedBalance;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JButton fundTransferButton;
    private static javax.swing.JLabel greetingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutLabel;
    private javax.swing.JButton viewTransactionsButton;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
