/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.mobileapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ralph
 */
public class homeFrame extends javax.swing.JFrame {

    private String fullName;
    private int clientId;
    private String firstName;
    private String balance;
    private String expectedBalance;

    /**
     * Creates new form homeFrame
     */
    public homeFrame() {
        initComponents();
    }

    public homeFrame(int userId) {
        this.clientId = userId;
        initComponents();
        
        if (Client.checkIfNew(clientId)) {
            JOptionPane.showMessageDialog(this, "Please change your password immediately", "Change Password", JOptionPane.WARNING_MESSAGE);
        }

        greetingLabel.setText("Hi, " + Client.getFirstName(clientId));
        fullNameLabel.setText(Client.createFullName(clientId));
        balanceLabel.setText(Client.getFormattedBalance(clientId));
        expectedBalLabel.setText(Client.getFormattedExpectedBalance(clientId));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        greetingLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        forExpectedBalance = new javax.swing.JLabel();
        forCurrentBalance = new javax.swing.JLabel();
        expectedBalLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        withdrawButton = new javax.swing.JButton();
        viewTransactionsButton = new javax.swing.JButton();
        fundTransferButton = new javax.swing.JButton();
        logoutLabel = new javax.swing.JButton();
        changePassButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("University Bank");
        setResizable(false);

        jPanel1.setLayout(null);

        greetingLabel.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        greetingLabel.setForeground(new java.awt.Color(255, 255, 255));
        greetingLabel.setText("Hi, Name");
        jPanel1.add(greetingLabel);
        greetingLabel.setBounds(40, 120, 220, 50);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 60, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/Untitled-8.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 420, 260);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/money (1).png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 270, 90, 80);

        fullNameLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        fullNameLabel.setText("Juan Dela Cruz");
        jPanel1.add(fullNameLabel);
        fullNameLabel.setBounds(130, 270, 220, 50);

        forExpectedBalance.setFont(new java.awt.Font("Calibri Light", 2, 14)); // NOI18N
        forExpectedBalance.setText("Expected Balance:");
        jPanel1.add(forExpectedBalance);
        forExpectedBalance.setBounds(130, 360, 120, 16);

        forCurrentBalance.setFont(new java.awt.Font("Calibri Light", 2, 14)); // NOI18N
        forCurrentBalance.setText("Current Balance:");
        jPanel1.add(forCurrentBalance);
        forCurrentBalance.setBounds(130, 340, 120, 16);

        expectedBalLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        expectedBalLabel.setForeground(new java.awt.Color(0, 153, 51));
        expectedBalLabel.setText("₱ 10,00.00");
        jPanel1.add(expectedBalLabel);
        expectedBalLabel.setBounds(260, 360, 110, 17);

        balanceLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(0, 153, 51));
        balanceLabel.setText("₱ 5,00.00");
        jPanel1.add(balanceLabel);
        balanceLabel.setBounds(260, 340, 110, 17);

        withdrawButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        withdrawButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/payment-method.png"))); // NOI18N
        withdrawButton.setText("Cash Withdrawal Request");
        withdrawButton.setBorder(null);
        withdrawButton.setRequestFocusEnabled(false);
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });
        jPanel1.add(withdrawButton);
        withdrawButton.setBounds(90, 540, 220, 40);

        viewTransactionsButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        viewTransactionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/return-to-the-past.png"))); // NOI18N
        viewTransactionsButton.setText("View Transaction History");
        viewTransactionsButton.setBorder(null);
        viewTransactionsButton.setRequestFocusEnabled(false);
        viewTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewTransactionsButton);
        viewTransactionsButton.setBounds(90, 440, 220, 40);

        fundTransferButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        fundTransferButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/cash-back.png"))); // NOI18N
        fundTransferButton.setText("Fund Transfer");
        fundTransferButton.setBorder(null);
        fundTransferButton.setRequestFocusEnabled(false);
        fundTransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundTransferButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fundTransferButton);
        fundTransferButton.setBounds(90, 490, 220, 40);

        logoutLabel.setBackground(java.awt.Color.lightGray);
        logoutLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        logoutLabel.setText("Logout");
        logoutLabel.setToolTipText("");
        logoutLabel.setBorder(null);
        logoutLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutLabelActionPerformed(evt);
            }
        });
        jPanel1.add(logoutLabel);
        logoutLabel.setBounds(280, 660, 90, 40);

        changePassButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        changePassButton.setText("Change Password");
        changePassButton.setBorder(null);
        changePassButton.setRequestFocusEnabled(false);
        changePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassButtonActionPerformed(evt);
            }
        });
        jPanel1.add(changePassButton);
        changePassButton.setBounds(90, 590, 220, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/BG_LandPage.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-10, 220, 480, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        this.dispose();
        new withdrawalFrame(this.clientId,this.firstName,this.fullName).setVisible(true);
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void viewTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTransactionsButtonActionPerformed

    private void fundTransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundTransferButtonActionPerformed
       this.dispose();
       new fundTransferFrame(this.clientId,this.firstName,this.fullName).setVisible(true);
    }//GEN-LAST:event_fundTransferButtonActionPerformed

    private void logoutLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutLabelActionPerformed
        this.dispose();
        new loginFrame().setVisible(true);
    }//GEN-LAST:event_logoutLabelActionPerformed

    private void changePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassButtonActionPerformed
        this.dispose();
        new changePasswordFrame(this.clientId, this.fullName, this.firstName).setVisible(true);
    }//GEN-LAST:event_changePassButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton changePassButton;
    private javax.swing.JLabel expectedBalLabel;
    private javax.swing.JLabel forCurrentBalance;
    private javax.swing.JLabel forExpectedBalance;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JButton fundTransferButton;
    private static javax.swing.JLabel greetingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutLabel;
    private javax.swing.JButton viewTransactionsButton;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
