/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.mobileapp;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ralph
 */
public class inputResetPasswordCode extends javax.swing.JFrame {
    
    private int accountId = 0;
    private String firstname = "";

    /**
     * Creates new form inputResetPasswordCode
     */
    public inputResetPasswordCode() {
        initComponents();
    }
    
    public inputResetPasswordCode(String email) {
        initComponents();
    }
    
    private boolean codeMatches(String code) {
        boolean match = false;
        System.out.println(code);
        try {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/ca_abs", "ca_abs", "haji12345");
            Statement st = con.createStatement();
            String DBQ = "SELECT * FROM CA_ABS.CLIENT WHERE RESET_PW_CODE='" + code + "'";
            ResultSet rs = st.executeQuery(DBQ);
            if (rs.next()) {
                match = true;
                this.accountId = rs.getInt("CLIENT_ID");
            } else {
                match = false;
            }
        } catch (ClassNotFoundException | SQLException | NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        return match;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        success = new javax.swing.JPanel();
        codeInput = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        success.setLayout(null);

        codeInput.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        codeInput.setForeground(java.awt.Color.lightGray);
        codeInput.setText("Enter code here");
        codeInput.setToolTipText("");
        codeInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codeInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codeInputFocusLost(evt);
            }
        });
        codeInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeInputKeyTyped(evt);
            }
        });
        success.add(codeInput);
        codeInput.setBounds(30, 420, 350, 60);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        success.add(cancelBtn);
        cancelBtn.setBounds(200, 500, 140, 50);

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        success.add(submitBtn);
        submitBtn.setBounds(60, 500, 140, 50);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Reset Password");
        success.add(jLabel10);
        jLabel10.setBounds(0, 0, 420, 230);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter password reset code");
        success.add(jLabel2);
        jLabel2.setBounds(20, 290, 370, 100);
        success.add(jLabel9);
        jLabel9.setBounds(40, 430, 70, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/BG_LandPage.jpg"))); // NOI18N
        success.add(jLabel5);
        jLabel5.setBounds(0, 220, 420, 530);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/Changepass_Banner.jpg"))); // NOI18N
        success.add(jLabel1);
        jLabel1.setBounds(0, -20, 416, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codeInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeInputFocusGained
        if (codeInput.getText().equals("Enter code here")) {
            codeInput.setText("");
            codeInput.setForeground(Color.black);
        }
    }//GEN-LAST:event_codeInputFocusGained

    private void codeInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeInputFocusLost
        if (codeInput.getText().equals("")) {
            codeInput.setText("Enter code here");
            codeInput.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_codeInputFocusLost

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
        new resetPasswordFrame().setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        if (codeMatches(codeInput.getText())) {
            JOptionPane.showMessageDialog(this, "Correct Password Code", "Reset Password", JOptionPane.INFORMATION_MESSAGE);
            new changePasswordFrame(this.accountId).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid password reset code", "Reset Password", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void codeInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeInputKeyTyped
        if (codeInput.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_codeInputKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputResetPasswordCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputResetPasswordCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputResetPasswordCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputResetPasswordCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputResetPasswordCode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField codeInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton submitBtn;
    private javax.swing.JPanel success;
    // End of variables declaration//GEN-END:variables
}
