/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.mobileapp;

import java.awt.Color;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Ralph
 */
public class loginFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form loginFrame
     */
    public loginFrame() {
        initComponents();
        usernameInput.grabFocus();
        this.setResizable(false);
    }
    private static String PW_hasher(String password) {
        String digest = "";
        if (password != null || (!password.isEmpty())) {
            MessageDigest m = null;
            try {
                m = MessageDigest.getInstance("MD5");
            } catch (Exception e) {

            }
            m.update(password.getBytes(), 0, password.length());
            digest = String.format("%032x", new BigInteger(1, m.digest()));

        }
        return digest;
    }
    
    private String createName(int accountId) {
        String fullname = "";
        try {
            String firstname,lastname,middlename;
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/ca_abs", "ca_abs", "haji12345");
            Statement st = con.createStatement();
            String DBQ = "SELECT * FROM CA_ABS.CLIENT WHERE CLIENT_ID="+accountId;
            ResultSet rs = st.executeQuery(DBQ);
            if (rs.next()) {
                firstname = rs.getString("CLIENT_FN");
                lastname = rs.getString("CLIENT_LN");
                middlename = rs.getString("CLIENT_MN");
                fullname = firstname +" "+ middlename.substring(0, 1) +". "+ lastname;
            } else {
                JOptionPane.showMessageDialog(this, "Username/Password is incorrect");
            }
        } catch (ClassNotFoundException | SQLException | NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        return fullname;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        signupButton = new javax.swing.JButton();
        forgotpassButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 70, 320, 270);

        usernameInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        usernameInput.setForeground(java.awt.Color.lightGray);
        usernameInput.setText("Username or Email Address");
        usernameInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameInputFocusLost(evt);
            }
        });
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        jPanel1.add(usernameInput);
        usernameInput.setBounds(20, 370, 360, 50);

        passwordInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordInput.setForeground(java.awt.Color.lightGray);
        passwordInput.setText("1234567890");
        passwordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordInputFocusLost(evt);
            }
        });
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        jPanel1.add(passwordInput);
        passwordInput.setBounds(20, 430, 360, 50);

        signupButton.setBackground(new java.awt.Color(51, 51, 51));
        signupButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        signupButton.setForeground(new java.awt.Color(255, 255, 255));
        signupButton.setText("Sign Up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        jPanel1.add(signupButton);
        signupButton.setBounds(20, 690, 160, 30);

        forgotpassButton.setBackground(new java.awt.Color(51, 51, 51));
        forgotpassButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        forgotpassButton.setForeground(new java.awt.Color(255, 255, 255));
        forgotpassButton.setText("Forgot Password?");
        forgotpassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotpassButtonActionPerformed(evt);
            }
        });
        jPanel1.add(forgotpassButton);
        forgotpassButton.setBounds(200, 690, 180, 30);

        loginButton.setBackground(new java.awt.Color(0, 176, 170));
        loginButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("LOG IN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton);
        loginButton.setBounds(20, 510, 360, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/Untitled-5.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed

    }//GEN-LAST:event_passwordInputActionPerformed

    private void usernameInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameInputFocusGained
        if (usernameInput.getText().equals("Username or Email Address")) {
            usernameInput.setText("");
            usernameInput.setForeground(Color.black);
        }
    }//GEN-LAST:event_usernameInputFocusGained

    private void usernameInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameInputFocusLost
        if (usernameInput.getText().equals("")) {
            usernameInput.setText("Username or Email Address");
            usernameInput.setForeground(Color.lightGray);
            usernameInput.setBorder(BorderFactory.createLineBorder(Color.red));
        } else {
            usernameInput.setBorder(BorderFactory.createLineBorder(Color.green));
        }
    }//GEN-LAST:event_usernameInputFocusLost

    private void passwordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordInputFocusGained
        if (passwordInput.getText().equals("1234567890")) {
            passwordInput.setText("");
            passwordInput.setForeground(Color.black);
        }
    }//GEN-LAST:event_passwordInputFocusGained

    private void passwordInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordInputFocusLost
        if (passwordInput.getText().equals("")) {
            passwordInput.setBorder(BorderFactory.createLineBorder(Color.red));
            passwordInput.setText("1234567890");
            passwordInput.setForeground(Color.lightGray);
        } else {
            passwordInput.setBorder(BorderFactory.createLineBorder(Color.green));
        }
    }//GEN-LAST:event_passwordInputFocusLost

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        new registerFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signupButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if (usernameInput.getText().isEmpty() || passwordInput.getText().isEmpty() || usernameInput.getText().equals("Username or Email Address") || passwordInput.getText().equals("1234567890")) {
            JOptionPane.showMessageDialog(this, "Username/Password is incorrect");
        } else {
            try {
                String password, username;
                password = PW_hasher(passwordInput.getText());
                username = usernameInput.getText();
                System.out.println(password);

                Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/ca_abs", "ca_abs", "haji12345");
                Statement st = con.createStatement();
                String DBQ = "SELECT * FROM CA_ABS.CLIENT WHERE CLIENT_UNAME='" + username + "' AND CLIENT_PW='" + password + "'";
                ResultSet rs = st.executeQuery(DBQ);
                if (rs.next()) {
                    String fullname = "",firstname = "";
                    JOptionPane.showMessageDialog(this, "Login Success");
                    int accountId = rs.getInt("CLIENT_ID");
                    fullname = createName(accountId);
                    firstname = rs.getString("CLIENT_FN");
                    this.dispose();
                    new landingFrame(accountId,firstname,fullname).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Username/Password is incorrect");
                }
            } catch (ClassNotFoundException | SQLException | NumberFormatException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void forgotpassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotpassButtonActionPerformed
        this.dispose();
        new resetPasswordFrame().setVisible(true);
    }//GEN-LAST:event_forgotpassButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                com.jtattoo.plaf.smart.SmartLookAndFeel.setTheme("Gray-Giant-Font", "INSERT YOUR LICENSE KEY HERE", "my company");
                javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new loginFrame().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forgotpassButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
