/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.mobileapp;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ralph
 */
public class viewWithdrawRequests extends javax.swing.JFrame {

    private int clientId;
    private DefaultTableModel model;

    /**
     * Creates new form viewWithdrawRequests
     */
    public viewWithdrawRequests() {
        initComponents();
    }

    public viewWithdrawRequests(int clientId) {
        this.clientId = clientId;
        initComponents();
        String[] columns = {"Date", "Amount", "PIN 2","STATUS"};
        model = new DefaultTableModel(columns, 0);
        populateModel(model);
        transactionsTable.setModel(model);
    }

    public void populateModel(DefaultTableModel Model) {
        try {
            int date = 0, pin2 = 0;
            double amount = 0, balance = 0;
            String formattedDate = "",status = "";
            ResultSet rs = Client.getWithdrawRequests(clientId);
            while (rs.next()) {
                date = rs.getInt("TIMEREQUEST");
                LocalDateTime expiryTime = LocalDateTime.ofEpochSecond(date, 0, ZoneOffset.of("+8"));
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("Y/M/d - hh:mm a");
                formattedDate = String.valueOf(expiryTime.plusMinutes(30).format(formatter));
                amount = rs.getDouble("AMOUNT");
                pin2 = rs.getInt("PIN2");
                switch(rs.getInt("STATUS")){
                    case 1: status = "Done";
                    case 2: status = "Cancelled";
                }
            }
            this.model.addRow(new Object[]{formattedDate, amount, pin2, status});
        } catch (SQLException ex) {
            Logger.getLogger(viewFundTransfersFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionsTable = new javax.swing.JTable();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        header = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Withdraw History");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        transactionsTable.setAutoCreateRowSorter(true);
        transactionsTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        transactionsTable.setToolTipText("");
        jScrollPane1.setViewportView(transactionsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 390, 430));

        title1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Withdraw Requests");
        jPanel1.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 410, 70));

        title2.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 255, 255));
        title2.setText("History");
        jPanel1.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 260, 100));

        Back.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, 90, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/BG_LandPage.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 420, 500));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/History_Banner.jpg"))); // NOI18N
        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.dispose();
        new viewTransactionsFrame(this.clientId).setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewWithdrawRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewWithdrawRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewWithdrawRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewWithdrawRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewWithdrawRequests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JTable transactionsTable;
    // End of variables declaration//GEN-END:variables
}
